events {}

http {
    upstream article_service_cluster {
        server articleservice1:8080;
        server articleservice2:8080;
        server articleservice3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://article_service_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}